### ISSUE TITLE
corrmap function not using all the datasets

### ISSUE THREAD

**Issue by evastone97** [sccn/corrmap#4]
Hello,

I have a study consisting of 54 datasets and I am using the CORRMAP function to find the common components between the three conditions that I have.

The problem is that CORRMAP is just using only a few of the datasets and not all the settings files that I have in the study. 

Therefore it ends up by giving me the common components of a subset of data and not all the data.

Do your think what might be the reason for that?

This is my study:
![image](https://user-images.githubusercontent.com/82998648/168430728-575892dd-086e-4219-8000-7e805413acf2.png)

And this is one of the results I am getting: and if you see in the number of datasets it says 18 because I have 18

I have 18 participants but the sets I have uploaded are 54 since each participant has 3 different conditions:

so the word - datasets is not correct, its better if was referring to subjects. so if i understood I have to load differently the data?
![image](https://user-images.githubusercontent.com/82998648/168430776-d6d2615d-3cbc-48c0-8b7c-636ec9518c0c.png)

I just found this conversation, maybe the answer is to have all the conditions in one set.
https://sccn.ucsd.edu/pipermail/eeglablist/2017/012020.html

Kind Regards,
Evangelia

**Comment by arnodelorme** [comment]
This is normal. If corrmap does not find a component in a dataset, it skips it.

**Comment by evastone97** [comment]
Yes, I see, but for example, set 22 is for subject 7(second condition). So that means it counts subject 7 with all its conditions? 

I am following this example and I have my datasets loaded like that. 
![image](https://user-images.githubusercontent.com/82998648/168464345-1c2d8e8a-78dc-425a-9d79-5e7348cae12f.png)
https://eeglab.org/tutorials/10_Group_analysis/component_clustering_tools.html

my study design:
![image](https://user-images.githubusercontent.com/82998648/168464602-6674b361-fb1f-47b2-8dfa-1a9e8ad1cb22.png)

So I want to use the corrmap to find components that can distinguish the conditions I have, is that correct?

**Comment by arnodelorme** [comment]
> So I want to use the corrmap to find components that can distinguish the conditions I have, is that correct?

Corrmap will only find components which are similar across subjects.

**Comment by evastone97** [comment]
Ok, I see.  Thanks for the answer!
So if I want to find similar components across different conditions what function would you suggest me to use?
Is this something that can be done only by visual inspection?

**Comment by arnodelorme** [comment]
You usually do not want to do that because otherwise you have a double dipping problem. You found differences between conditions, but you searched for components which were specific to that condition.

**Comment by evastone97** [comment]
true that was my thought to search for components that are specific to that condition. 

so other than the CORRMAP function,  can I use EEGLAB STATs to find the components that are significant? (sorry I might be a bit confused now)
